version: "3.9"
services:
  web:
    build: ./web
    container_name: web_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
  nodeapp:
    build:
      context: ./server
    ports:
      - "3000:3000"
    container_name: node_app
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  jenkins:
    build: 
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    user: root
    volumes:
      - ../volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Optional for Docker builds
    networks:
      - jenkins_network
    restart: unless-stopped
networks:
  jenkins_network:
    driver: bridge
volumes:
  jenkins_home: {}